[package]
name = "tps6699x"
version = "0.1.0"
edition = "2021"
license = "MIT"
rust-version = "1.83"

[dependencies]
embedded-hal-async = "1.0.0"
embedded-hal = "1.0.0"
embedded-usb-pd = { path = "../embedded-usb-pd", default-features = false, features = [
    "defmt",
] }
device-driver = { version = "=1.0.0-rc.1", default-features = false, features = [
    "yaml",
] }
defmt = { version = "0.3.0", optional = true }
embassy-sync = { git = "https://github.com/embassy-rs/embassy", optional = true }
embassy-time = { git = "https://github.com/embassy-rs/embassy", optional = true }
embedded-io-async = "0.6.1"

[features]
default = ["defmt"]
defmt = [
    "dep:defmt",
    "device-driver/defmt-03",
    "embassy-sync/defmt",
    "embassy-time/defmt",
    "embassy-time/defmt-timestamp-uptime",
]
embassy = ["dep:embassy-sync", "dep:embassy-time"]

[dev-dependencies]
embedded-hal-mock = { version = "0.11.1", features = ["embedded-hal-async"] }
tokio = { version = "1.42.0", features = ["rt", "macros"] }
