
# cargo-vet audits file

[[audits.aquamarine]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.6.0"

[[audits.embassy-time]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.5.0"

[[audits.include_dir]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.7.4"

[[audits.include_dir_macros]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.7.4"

[[audits.itertools]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.10.5"

[[audits.portable-atomic]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "1.11.1"

[[audits.static_cell]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "2.1.1"
