
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.OpenDevicePartnership]
url = "https://raw.githubusercontent.com/OpenDevicePartnership/rust-crate-audits/main/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/rust-crate-audits/main/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[policy.embassy-sync]
audit-as-crates-io = false

[policy.embassy-time]
audit-as-crates-io = false

[policy.embassy-time-driver]
audit-as-crates-io = false

[[exemptions.addr2line]]
version = "0.24.2"
criteria = "safe-to-run"

[[exemptions.ahash]]
version = "0.8.12"
criteria = "safe-to-deploy"

[[exemptions.anyhow]]
version = "1.0.98"
criteria = "safe-to-deploy"

[[exemptions.arraydeque]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.backtrace]]
version = "0.3.75"
criteria = "safe-to-run"

[[exemptions.bincode]]
version = "2.0.1"
criteria = "safe-to-deploy"

[[exemptions.bincode_derive]]
version = "2.0.1"
criteria = "safe-to-deploy"

[[exemptions.bitfield]]
version = "0.19.0"
criteria = "safe-to-deploy"

[[exemptions.bitfield-macros]]
version = "0.19.0"
criteria = "safe-to-deploy"

[[exemptions.bitvec]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.convert_case]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.critical-section]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.dd-manifest-tree]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.defmt]]
version = "0.3.100"
criteria = "safe-to-deploy"

[[exemptions.defmt]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.defmt-macros]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.defmt-parser]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.device-driver]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.device-driver-generation]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.device-driver-macros]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.embedded-hal]]
version = "0.2.7"
criteria = "safe-to-deploy"

[[exemptions.embedded-hal]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.embedded-hal-async]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.embedded-hal-mock]]
version = "0.11.1"
criteria = "safe-to-run"

[[exemptions.embedded-hal-nb]]
version = "1.0.0"
criteria = "safe-to-run"

[[exemptions.embedded-io]]
version = "0.6.1"
criteria = "safe-to-deploy"

[[exemptions.embedded-io-async]]
version = "0.6.1"
criteria = "safe-to-deploy"

[[exemptions.embedded-time]]
version = "0.12.1"
criteria = "safe-to-run"

[[exemptions.funty]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.futures-core]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-sink]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.gimli]]
version = "0.31.1"
criteria = "safe-to-run"

[[exemptions.hash32]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.14.5"
criteria = "safe-to-deploy"

[[exemptions.hashlink]]
version = "0.9.1"
criteria = "safe-to-deploy"

[[exemptions.heapless]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.itertools]]
version = "0.14.0"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.172"
criteria = "safe-to-run"

[[exemptions.log]]
version = "0.4.27"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.7.4"
criteria = "safe-to-run"

[[exemptions.miniz_oxide]]
version = "0.8.8"
criteria = "safe-to-run"

[[exemptions.num]]
version = "0.3.1"
criteria = "safe-to-run"

[[exemptions.num-complex]]
version = "0.3.1"
criteria = "safe-to-run"

[[exemptions.num-iter]]
version = "0.1.45"
criteria = "safe-to-run"

[[exemptions.num-rational]]
version = "0.3.2"
criteria = "safe-to-run"

[[exemptions.object]]
version = "0.36.7"
criteria = "safe-to-run"

[[exemptions.once_cell]]
version = "1.21.3"
criteria = "safe-to-deploy"

[[exemptions.pin-project-lite]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.pin-utils]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-error-attr2]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-error2]]
version = "2.0.1"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2]]
version = "1.0.95"
criteria = "safe-to-deploy"

[[exemptions.radium]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.101"
criteria = "safe-to-deploy"

[[exemptions.tap]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.thiserror]]
version = "2.0.12"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "2.0.12"
criteria = "safe-to-deploy"

[[exemptions.tokio]]
version = "1.45.0"
criteria = "safe-to-run"

[[exemptions.tokio-macros]]
version = "2.5.0"
criteria = "safe-to-run"

[[exemptions.unty]]
version = "0.0.4"
criteria = "safe-to-deploy"

[[exemptions.version_check]]
version = "0.9.5"
criteria = "safe-to-deploy"

[[exemptions.virtue]]
version = "0.0.18"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_aarch64_msvc]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_i686_gnu]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_i686_gnullvm]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_i686_msvc]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_gnu]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_msvc]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.wyz]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.yaml-rust2]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.zerocopy]]
version = "0.8.25"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.8.25"
criteria = "safe-to-deploy"
